### ISSUE TITLE
cannot find file finalb.h5

### ISSUE THREAD

**Issue by yujianyuanhaha** [AirSimDroneSimulator/AirSim#1]
Thanks for your great job, I am refer to the codes for coursework final project.
when I try to run `main.ipynb` file within /DQN folder, it pop error like ` Unable to open file (unable to open file: name = 'finalb.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)`. Seems like it miss the `.h5` file.
By any chance you could share the  `finalb.h5` file?
Thanks

**Comment by zhangrh93** [comment]
h5 files contains parameters for model (structure and weights of neural network). This line is used to load saved models. We didn't upload trained models, so this line is useless, you can simply delete this line and set variable "model" to None (It will be set to a new initialized neural network).

Due to some limitations, we did not upload any trained models, but we can guarantee that parameters in the notebook really works. It usually takes several hours to get a good policy.  

Please use the notebook in [3D_path_finding](../tree/master/3D_path_finding):
 [GridWorld.ipynb](../tree/master/3D_path_finding/GridWorld.ipynb),
 [HeightControl.ipynb](../tree/master/3D_path_finding/HeightControl.ipynb) and
 [ImgConrtol.ipynb](../tree/master/3D_path_finding/ImgConrtol.ipynb).
These are codes used to start your training for all three tasks.
